config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  get "about", to: "about_page#show"

  resources :products
  resources :customers
  resources :dogs

  # get "customers/index"
  # get "customers/show"
  # get "dogs/index"
  # get "dogs/show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :dogs
  has_many :customer_products
  has_many :products, through: :customer_products

  validates :first_name, :last_name, :age, presence: true
  validates :age, numericality: { only_integer: true, greater_than: 0 }

  def self.search(search)
    if search.present?
      Customer.where("first_name LIKE ? OR last_name LIKE ?", "%#{search}%", "%#{search}%")
    else
      @customers = Customer.all
    end
  end
end

app/models/customer_product.rb
class CustomerProduct < ApplicationRecord
  belongs_to :customer
  belongs_to :product
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :customer, optional: true

  validates :main_breed, :dog_name, presence: true

  def self.search(search)
    if search.present?
      Dog.where("dog_name LIKE ?", "%#{search}%")
    else
      @dogs = Dog.all
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :customer_products
  has_many :customers, through: :customer_products

  validates :product_name, :category, :price, :description, presence: true
  validates :price, numericality: {greater_than: 0}

  def self.search(search)
    if search.present?
      Product.where("product_name LIKE ?", "%#{search}%")
    else
      @products = Product.all
    end
  end

end

app/controllers/about_page_controller.rb
class AboutPageController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.search(params[:search]).page(params[:page]).per(20)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, last_name, :id, :search)
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.search(params[:search]).page(params[:page]).per(20)
  end

  def show
    @dog = Dog.find(params[:id])
  end

  private

  def dog_params
    params.require(:dog).permit(:dog_name, :id, :search)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @customers = Customer.all.limit(5)

    @products = Product.all.limit(5)

    @dogs = Dog.all.limit(5)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.search(params[:search]).page(params[:page]).per(20)
  end

  def show
    @product = Product.find(params[:id])
  end

  private

  def product_params
    params.require(:product).permit(:product_name, :id, :search)
  end
end

app/helpers/about_page_helper.rb
module AboutPageHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pagination_helper.rb
module PaginationHelper
  def paginate(collection, page, per_page = 20)
    offset = (page - 1) * per_page
    collection.limit(per_page).offset(offset)
  end

  def next_page(collection, chosen_path, per_size = 20)
    links = ""
    page = params[:page].to_i
    next_link = page == 0 ? 2 : page + 1

    if collection.size == per_size
      links = link_to "Next", send(chosen_path, page: next_link)
    end
  end

  def previous_page(collection, chosen_path, per_size = 20)
    links = ""
    page = params[:page].to_i
    previous_link = page - 1

    if page > 1
      links = link_to "Previous", send(chosen_path, page: previous_link)
    end
  end
end

# Source: https://www.geeksforgeeks.org/how-to-implement-pagination-in-ruby-on-rails/

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/about_page/show.html.erb
<div class="container">
  <div class="row my-5">
    <div class="col">
      <h1>About</h1>
    </div>
  </div>

  <div class="row">
    <div class="d-flex justify-content-center">
      <span class="border">
        <%= image_tag ("ERD.png"), alt: "An ERD diagram for database" %>
      </span>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col">
      <div>
        <h3><%= link_to 'Customers Table', customers_path, :class => "text-reset link-primary link-offset-2 link-underline link-underline-opacity-0" %></h3>
        <p>
          This table stores the customer's information, such as their first and last name, and age.
          <br>The data is taken from <a href="https://github.com/faker-ruby/faker">Faker</a>,
          which is a tool for generating fake data.
        </p>

        <h3><%= link_to 'Dogs Table', dogs_path, :class => "text-reset link-primary link-offset-2 link-underline link-underline-opacity-0" %></h3>
        <p>This table stores the dog's information, such as their main breed, sub breed, name, and a reference to the Customer table.
          <br>The data is taken from <a href="https://dog.ceo/dog-api/">Dog API</a> website.
        </p>

        <h3><%= link_to 'Products Table', products_path, :class => "text-reset link-primary link-offset-2 link-underline link-underline-opacity-0" %></h3>
        <p>This table stores the product's information, such as their name, category, price, and description.
          <br>The data is taken from <a href="https://www.kaggle.com/datasets/bhavikjikadara/grocery-store-dataset">Kaggle</a> website by
          <a href="https://www.kaggle.com/bhavikjikadara">Bhavik Jikadara</a>, which is data originally from Costco's online marketplace.
        </p>

        <h3>Customer Product</h3>
        <p>
          This table stores the entries linking a customer to the product they have purchased.
          <br>The data is created based on what the customer has purchased.
        </p>
      </div>
    </div>
  </div>
</div>

app/views/customers/index.html.erb
<div class="container">
  <div class="row my-3 d-flex justify-content-end">
    <div class="col-auto">
      <%= form_tag customers_url, :method => "get" do %>
      <%= label_tag(:search, "Search for a customer:") %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag("Search") %>
      <% end %>
    </div>
  </div>

  <div class="col d-flex justify-content-center">
    <h1>Customers</h1>
  </div>

  <div class="row px-5">
    <div class="col d-flex justify-content-center">
      <ol class="list-group list-group-flush" style="width: 18rem;">
        <% @customers.each do |customer| %>
          <li class="list-group-item d-flex justify-content-center">
            <%= link_to "#{customer.first_name} #{customer.last_name}", customer_path(customer),
            :class => "text-reset link-primary link-offset-2 link-underline link-underline-opacity-0" %>
          </li>
        <% end %>
      </ol>
    </div>
  </div>

  <div class="mt-3 d-flex justify-content-center">
        <%= paginate @customers%>
  </div>
</div>

app/views/customers/show.html.erb
<div class="container">
  <div class="row my-5">
    <div class="col">
      <h1><%= "#{@customer.first_name} #{@customer.last_name}"%></h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <h3>This customer has <%= @customer.dogs.count %> dogs: </h3>
      <ul>
        <% @customer.dogs.each do |dog|%>
          <li><%= link_to dog.dog_name, dog %> </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col">
      <h3>This customer has <%= @customer.products.count %> products in his cart:</h3>
      <div>
          <ul>
              <% @customer.products.each do |product| %>
                  <li><%= link_to product.product_name, product %></li>
              <% end %>
          </ul>
      </div>
    </div>
  </div>
</div>

app/views/dogs/index.html.erb
<div class="container">
  <div class="row my-3 d-flex justify-content-end">
    <div class="col-auto">
      <%= form_tag dogs_url, :method => "get" do %>
        <%= label_tag(:search, "Search for a dog:") %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag("Search", :dog_name => nil)%>
      <% end %>
    </div>
  </div>

  <div class="col d-flex justify-content-center">
    <h1>Dogs</h1>
  </div>
  <div class="row px-5">
    <div class="col d-flex justify-content-center">
      <ol class="list-group list-group-flush" style="width: 18rem;">
        <% @dogs.each do |dog| %>
          <li class="list-group-item d-flex justify-content-center">
            <%= link_to dog.dog_name, dog,
            :class => "text-reset link-primary link-offset-2 link-underline link-underline-opacity-0" %>
          </li>
        <% end %>
      </ol>
    </div>
  </div>

  <div class="mt-3 d-flex justify-content-center">
    <%= paginate @dogs %>
  </div>
</div>

app/views/dogs/show.html.erb
<div class="container">
    <div class="row my-5">
        <div class="col">
            <h1><%= @dog.dog_name %></h1>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <p>
                <%= @dog.dog_name %> is a
                <strong>
                    <%= @dog.sub_breed ? @dog.sub_breed : ''%> <%= @dog.main_breed %>
                </strong>
            </p>
            <p>
                This dog belongs to <%= link_to @dog.customer.first_name, customer_path(@dog.customer) %>
            </p>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<div class="container">
    <div class="row my-5">
        <div class="col d-flex justify-content-center">
            <h1>Welcome to our Intro to Rails Project!</h1>
        </div>
    </div>

    <div class="row">
        <div class="col px-5">
            <p>Our Intro to Rails Project features 4 tables: Product, Customer, Dogs, and CustomerProducts. We used a mixture of Faker, CSV, and JSON files in order to fill our database. A customer will be able to buy multiple products and own multiple dogs. Many products can be bought by many customers. A dog is owned by only one customer.</p>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= content_for(:title) || "Intro To Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <%= link_to 'Intro to Rails', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
              <%= link_to 'About', about_path, class: 'nav-link' %>
            </li>

            <li class="nav-item">
              <%= link_to 'Customers', customers_path, class: 'nav-link' %>
            </li>

            <li class="nav-item">
              <%= link_to 'Products', products_path, class: 'nav-link' %>
            </li>

            <li class="nav-item">
              <%= link_to 'Dogs', dogs_path, class: 'nav-link' %>
            </li>

          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
          <%= yield %>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<div class="container">
  <div class="row my-3 d-flex justify-content-end">
    <div class="col-auto">
      <div class="container">
            <%= form_tag products_url, :method => "get" do %>
            <%= label_tag(:search, "Search for product:") %>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag("Search", :product_name => nil)%>
            <% end %>
      </div>
    </div>
  </div>

  <div class="col d-flex justify-content-center">
    <h1>Products</h1>
  </div>
  <div class="row px-5">
    <div class="col d-flex justify-content-center">
      <ol class="list-group list-group-flush" style="width: 50rem;">
        <% @products.each do |product| %>
         <li class="list-group-item d-flex justify-content-center">
          <%= link_to product.product_name, product,
            :class => "text-reset link-primary link-offset-2 link-underline link-underline-opacity-0" %>
        </li>
        <% end %>
      </ol>
    </div>
  </div>
  <div class="mt-3 d-flex justify-content-center">
    <%= paginate @products %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
    <div class="row my-5">
        <div class="col">
            <h1><%= @product.product_name %></h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <p>
                <strong>Category:</strong> 
                <%= @product.category%>
            </p>
        </div>
        <div class="col-md">
            <p>
                <strong>Price:</strong> 
                <%= @product.price%>
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <p>
                <strong>Description:</strong>
                <br>
                <%= @product.description%>
            </p>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col">
            <h3>Customers who bought this product:</h3>
            <div>
                <ul>
                    <% @product.customers.each do |customer| %>
                        <li><%= link_to "#{customer.first_name} #{customer.last_name}", customer %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</div>